[colors.primary]
background = "#191114"
foreground = "#efdfe2"

[colors.cursor]
cursor = "#ffb0cb"
text = "#541d34"

[colors.selection]
background = "#5a3f48"
text = "#ffd9e4"

[colors.normal]
black   = "#261d20"
red     = "#ffb4ab"
green   = "#ffb0cb"
yellow  = "#e2bdc8"
blue    = "#f0bc95"
magenta = "#ffb0cb"
cyan    = "#e2bdc8"
white   = "#efdfe2"

[colors.bright]
black   = "#31282a"
red     = "#ffb4ab"
green   = "#ffb0cb"
yellow  = "#e2bdc8"
blue    = "#f0bc95"
magenta = "#ffb0cb"
cyan    = "#e2bdc8"
white   = "#d5c2c6"
