[colors.primary]
background = "#161217"
foreground = "#eae0e7"

[colors.cursor]
cursor = "#e5b6f2"
text = "#452153"

[colors.selection]
background = "#514254"
text = "#f1dcf3"

[colors.normal]
black   = "#231e23"
red     = "#ffb4ab"
green   = "#e5b6f2"
yellow  = "#d5c0d7"
blue    = "#f5b7b4"
magenta = "#e5b6f2"
cyan    = "#d5c0d7"
white   = "#eae0e7"

[colors.bright]
black   = "#2d282e"
red     = "#ffb4ab"
green   = "#e5b6f2"
yellow  = "#d5c0d7"
blue    = "#f5b7b4"
magenta = "#e5b6f2"
cyan    = "#d5c0d7"
white   = "#cec3cd"
