[colors.primary]
background = "#141318"
foreground = "#e6e1e9"

[colors.cursor]
cursor = "#cdbdff"
text = "#34275e"

[colors.selection]
background = "#494458"
text = "#e7def8"

[colors.normal]
black   = "#201f24"
red     = "#ffb4ab"
green   = "#cdbdff"
yellow  = "#cbc3dc"
blue    = "#eeb8c9"
magenta = "#cdbdff"
cyan    = "#cbc3dc"
white   = "#e6e1e9"

[colors.bright]
black   = "#2b292f"
red     = "#ffb4ab"
green   = "#cdbdff"
yellow  = "#cbc3dc"
blue    = "#eeb8c9"
magenta = "#cdbdff"
cyan    = "#cbc3dc"
white   = "#cac4cf"
