[colors.primary]
background = "#17130b"
foreground = "#eae1d4"

[colors.cursor]
cursor = "#e7c26c"
text = "#3e2e00"

[colors.selection]
background = "#52452a"
text = "#f4e0bb"

[colors.normal]
black   = "#231f17"
red     = "#ffb4ab"
green   = "#e7c26c"
yellow  = "#d7c5a0"
blue    = "#afcfab"
magenta = "#e7c26c"
cyan    = "#d7c5a0"
white   = "#eae1d4"

[colors.bright]
black   = "#2e2921"
red     = "#ffb4ab"
green   = "#e7c26c"
yellow  = "#d7c5a0"
blue    = "#afcfab"
magenta = "#e7c26c"
cyan    = "#d7c5a0"
white   = "#d0c5b4"
