-- Generated by Matugen
local colors = {
    bg      = '{{colors.surface.default.hex}}',
    fg      = '{{colors.on_surface.default.hex}}',
    primary = '{{colors.primary.default.hex}}',
    sec     = '{{colors.secondary.default.hex}}',
    ter     = '{{colors.tertiary.default.hex}}',
    err     = '{{colors.error.default.hex}}',
    surf    = '{{colors.surface_container.default.hex}}',
    on_surf = '{{colors.on_surface_variant.default.hex}}',
    accent  = '{{colors.primary_container.default.hex}}',
}

-- Clear existing highlights
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
    vim.cmd("syntax reset")
end

vim.g.colors_name = "matugen"

local hl = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
end

-- UI Highlights (Standard M3 mapping)
hl("Normal",       { fg = colors.fg, bg = colors.bg })
hl("CursorLine",   { bg = colors.surf })
hl("Visual",       { bg = colors.accent })
hl("Search",       { fg = colors.bg, bg = colors.sec })
hl("StatusLine",   { fg = colors.fg, bg = colors.surf })
hl("VertSplit",    { fg = colors.surf })

-- Syntax Highlights
hl("Comment",      { fg = colors.on_surf, italic = true })
hl("Keyword",      { fg = colors.primary, bold = true })
hl("Function",     { fg = colors.ter })
hl("String",       { fg = colors.sec })
hl("Number",       { fg = colors.ter })
hl("Type",         { fg = colors.primary })
hl("Identifier",   { fg = colors.fg })
hl("Error",        { fg = colors.err, bold = true })

-- Diagnostic Highlights
hl("DiagnosticError", { fg = colors.err })
hl("DiagnosticWarn",  { fg = colors.sec })
