-- Generated by Matugen
local colors = {
    bg      = '#191114',
    fg      = '#eedfe3',
    primary = '#feb0d2',
    sec     = '#e0bdca',
    ter     = '#f2bb99',
    err     = '#ffb4ab',
    surf    = '#251d20',
    on_surf = '#d4c2c8',
    accent  = '#6d3350',
}

-- Clear existing highlights
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
    vim.cmd("syntax reset")
end

vim.g.colors_name = "matugen"

local hl = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
end

-- UI Highlights (Standard M3 mapping)
hl("Normal",       { fg = colors.fg, bg = "NONE" })
hl("CursorLine",   { bg = colors.surf })
hl("Visual",       { bg = colors.accent })
hl("Search",       { fg = colors.bg, bg = colors.sec })
hl("StatusLine",   { fg = colors.fg, bg = colors.surf })
hl("VertSplit",    { fg = colors.surf })

-- Syntax Highlights
hl("Comment",      { fg = colors.on_surf, italic = true })
hl("Keyword",      { fg = colors.primary, bold = true })
hl("Function",     { fg = colors.ter })
hl("String",       { fg = colors.sec })
hl("Number",       { fg = colors.ter })
hl("Type",         { fg = colors.primary })
hl("Identifier",   { fg = colors.fg })
hl("Error",        { fg = colors.err, bold = true })

-- Diagnostic Highlights
hl("DiagnosticError", { fg = colors.err })
hl("DiagnosticWarn",  { fg = colors.sec })
