[colors]
;; Main Background/Foreground
background = #17130b
foreground = #eae1d4

;; Accent Colors
primary = #e7c26c
secondary = #d7c5a0
tertiary = #afcfab

;; State Colors
alert = #ffb4ab
disabled = #999080

;; Transparency (Optional: adding 2-digit hex for 80% alpha)
background-alt = #231f17cc
