[colors]
;; Main Background/Foreground
background = #1a1110
foreground = #f1dedd

;; Accent Colors
primary = #ffb3ad
secondary = #e7bdb9
tertiary = #e1c28c

;; State Colors
alert = #ffb4ab
disabled = #a08c8a

;; Transparency (Optional: adding 2-digit hex for 80% alpha)
background-alt = #271d1ccc
