[colors]
;; Main Background/Foreground
background = #12140d
foreground = #e3e3d7

;; Accent Colors
primary = #b9cf84
secondary = #c2caaa
tertiary = #a1d0c7

;; State Colors
alert = #ffb4ab
disabled = #909284

;; Transparency (Optional: adding 2-digit hex for 80% alpha)
background-alt = #1f2019cc
