[colors]
;; Main Background/Foreground
background = #191113
foreground = #efdfe1

;; Accent Colors
primary = #ffb1c6
secondary = #e3bdc6
tertiary = #eebd93

;; State Colors
alert = #ffb4ab
disabled = #9e8c90

;; Transparency (Optional: adding 2-digit hex for 80% alpha)
background-alt = #261d1fcc
