;==========================================================
; POLYBAR by Ayush
;==========================================================

include-file = ~/.config/polybar/colors.ini
# [colors]
# background
# foreground
# primary - accent
# secondary - accent
# tertiary - accent
# alert - state
# disabled - state
# background-alt - transparent

include-file = ~/.config/polybar/modules.ini

[bar/primary]
width = 100%
monitor = ${env:MONITOR:}
height = 42

modules-center = left-pill sep_space tray sep_space right-pill
modules-left = left-pill sep_space xworkspaces sep xwindow sep_space right-pill
modules-right = left-pill pulseaudio sep_space date sep battery sep_space right-pill

border-top-size = 5pt
border-bottom-size = 5pt
border-size = 0pt

; Use the colors from our template
background = #00000000
foreground = ${colors.foreground}

# Your standard text font
font-0 = "JetBrainsMono NL :size=14;3"
font-1 = "JetBrainsMono NL :size=18;3"
font-2 = "Symbols Nerd Font Mono :size=18;3"
font-3 = "Symbols Nerd Font Mono :size=33;6"
font-4 = "Symbola:size=10;2"

cursor-click = pointer
cursor-scroll = ns-resize


[bar/secondary]
width = 100%
monitor = ${env:MONITOR:}
height = 42

modules-left = left-pill sep_space xworkspaces sep xwindow sep_space right-pill
modules-right = left-pill sep_space pulseaudio sep memory sep cpu sep date sep_space right-pill

border-top-size = 5pt
border-bottom-size = 5pt
border-size = 0pt

; Use the colors from our template
background = #00000000
foreground = ${colors.foreground}

# Your standard text font
font-0 = "JetBrainsMono NL :size=14;3"
font-1 = "JetBrainsMono NL :size=18;3"
font-2 = "Symbols Nerd Font Mono :size=18;3"
font-3 = "Symbols Nerd Font Mono :size=33;6"

cursor-click = pointer
cursor-scroll = ns-resize


[setting]
pseudo-transparency = true



